CREATE TABLE "ajis_anak" (
	"id_anak" varchar(25) PRIMARY KEY NOT NULL,
	"nik" varchar(50),
	"nama_lengkap" varchar(150) NOT NULL,
	"nama_panggilan" varchar(50),
	"agama" varchar(50),
	"jns_kel" varchar(1),
	"tempat_lahir" varchar(30),
	"tgl_lahir" date,
	"anak_ke" integer,
	"dari_saudara" integer,
	"alamat" varchar(100),
	"propid" varchar(4),
	"nama_propinsi" varchar(30),
	"kabid" varchar(4),
	"nama_kabupaten" varchar(30),
	"camatid" varchar(10),
	"nama_kecamatan" varchar(30),
	"desaid" varchar(10),
	"nama_desa" varchar(30),
	"jenjang_pendidikan" varchar(10),
	"kelas" varchar(50),
	"nama_sekolah" text,
	"alamat_sekolah" text,
	"jurusan" varchar(30),
	"semester" integer,
	"nama_pt" text,
	"alamat_pt" text,
	"nilai" varchar(50),
	"pelajaran_favorit" varchar(50),
	"jarak_rumah" varchar(50),
	"alat_transportasi" varchar(50),
	"hobi" text,
	"prestasi" text,
	"no_rekening" varchar(25),
	"pemilik_rekening" varchar(50),
	"nama_bank" varchar(50),
	"foto" text,
	"no_kartu_keluarga" varchar(25),
	"asnaf" varchar(50),
	"status_ortu" varchar(50),
	"status_survey" boolean DEFAULT false NOT NULL,
	"status_kelayakan" boolean DEFAULT false NOT NULL,
	"status_anak_juara" varchar(3),
	"status_tersantuni" varchar(2),
	"status_pinjam" boolean DEFAULT false NOT NULL,
	"status_mentor" boolean DEFAULT false NOT NULL,
	"aktif" boolean DEFAULT true NOT NULL,
	"alumni_juara" boolean,
	"juara" varchar(10),
	"approval_ijf" varchar(50),
	"via_input" varchar(100),
	"id_wilayah_pembinaan" bigint,
	"nama_wilayah" varchar(100),
	"kantor_id" varchar(10),
	"nama_kantor" varchar(100),
	"id_sdm" bigint,
	"nama_mentor" varchar(100),
	"tgl_terdaftar" date,
	"tgl_pengajuan" date,
	"nama_lengkap_ayah" varchar(50),
	"alamat_ayah" varchar(100),
	"propid_ayah" varchar(4),
	"nama_propinsi_ayah" varchar(30),
	"kabid_ayah" varchar(4),
	"nama_kabupaten_ayah" varchar(30),
	"camatid_ayah" varchar(10),
	"nama_kecamatan_ayah" varchar(30),
	"desaid_ayah" varchar(10),
	"nama_desa_ayah" varchar(30),
	"pekerjaan_ayah" text,
	"penghasilan_rata_rata_ayah" numeric(20, 2),
	"tanggal_kematian_ayah" date,
	"penyebab_kematian_ayah" varchar(100),
	"nama_lengkap_ibu" varchar(50),
	"alamat_ibu" varchar(100),
	"propid_ibu" varchar(4),
	"nama_propinsi_ibu" varchar(30),
	"kabid_ibu" varchar(4),
	"nama_kabupaten_ibu" varchar(30),
	"camatid_ibu" varchar(10),
	"nama_kecamatan_ibu" varchar(30),
	"desaid_ibu" varchar(10),
	"nama_desa_ibu" varchar(30),
	"pekerjaan_ibu" text,
	"penghasilan_rata_rata_ibu" numeric(20, 2),
	"tanggal_kematian_ibu" date,
	"penyebab_kematian_ibu" varchar(100),
	"nama_lengkap_wali" varchar(50),
	"alamat_wali" varchar(100),
	"propid_wali" varchar(4),
	"nama_propinsi_wali" varchar(30),
	"kabid_wali" varchar(4),
	"nama_kabupaten_wali" varchar(30),
	"camatid_wali" varchar(10),
	"nama_kecamatan_wali" varchar(30),
	"desaid_wali" varchar(10),
	"nama_desa_wali" varchar(30),
	"pekerjaan_wali" text,
	"penghasilan_rata_rata_wali" numeric(20, 2),
	"telp_yang_bisa_dihubungi" varchar(15),
	"atas_nama" varchar(30),
	"hubungan_kerabat" varchar(15),
	"tinggal_bersama" text,
	"nama_tinggal" text,
	"ket_tinggal" text,
	"penghasilan_tinggal" numeric(20, 2),
	"pekerjaan_tinggal" text,
	"tidak_serumah_ortu" boolean,
	"nia_rfo_book" varchar(50),
	"nama_rfo_book" varchar(100),
	"tgl_peminjaman" date,
	"tgl_expired" date,
	"book_via" varchar(50),
	"user_book" varchar(50),
	"external_ids" jsonb,
	CONSTRAINT "ajis_anak_nik_unique" UNIQUE("nik"),
	CONSTRAINT "ajis_anak_jns_kel_check" CHECK (jns_kel IS NULL OR jns_kel IN ('l', 'p')),
	CONSTRAINT "ajis_anak_status_aj_check" CHECK (status_anak_juara IS NULL OR status_anak_juara IN ('caj', 'aj', 'non')),
	CONSTRAINT "ajis_anak_status_tersantuni_check" CHECK (status_tersantuni IS NULL OR status_tersantuni IN ('su', 'b', 'se', 't'))
);
--> statement-breakpoint
CREATE TABLE "ajis_data_prestasi" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"id_anak" varchar(25) NOT NULL,
	"event_lomba" varchar(100),
	"tgl" date,
	"lokasi" varchar(50),
	"skala_prestasi_tingkat" varchar(30),
	"capaian_prestasi" varchar(50),
	"jenis_bidang" varchar(30),
	"publikasi_media" varchar(50),
	"semesterid" varchar(10),
	"laporanid" varchar(50),
	"bulan" varchar(2),
	"tahun" varchar(4),
	"show" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ajis_opname" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"tahun" smallint NOT NULL,
	"id_pemasangan_baru" varchar(100) NOT NULL,
	"id_anak" varchar(25),
	"id_donatur" varchar(30),
	"program_donasi" varchar(100),
	"id_program" bigint,
	"saldo_awal_ganjil" numeric(20, 2),
	"tupo_jan_jun" varchar(100),
	"date_opname_ganjil" timestamp with time zone,
	"user_opname_ganjil" varchar(100),
	"saldo_akhir_ganjil" numeric(20, 2),
	"saldo_awal_genap" numeric(20, 2),
	"tupo_jul_des" varchar(100),
	"date_opname_genap" timestamp with time zone,
	"user_opname_genap" varchar(100),
	"saldo_akhir_genap" numeric(20, 2),
	"kantor_id" varchar(10),
	"keterangan" text,
	"user_input" varchar(50),
	"user_update" varchar(100),
	"updated" timestamp with time zone,
	"external_ids" jsonb
);
--> statement-breakpoint
CREATE TABLE "ajis_pemasangan" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"id_pemasangan_baru" varchar(100) NOT NULL,
	"tahun" smallint NOT NULL,
	"tgl_pemasangan" date,
	"tgl_pemberhentian_pemasangan" date,
	"id_donatur" varchar(30),
	"nama_donatur" varchar(150),
	"nia_rfo" varchar(50),
	"nama_rfo" varchar(150),
	"id_anak" varchar(25) NOT NULL,
	"nama_anak" varchar(150),
	"jns_kel" varchar(1),
	"kelas" varchar(50),
	"jenjang_pendidikan" varchar(10),
	"asnaf" varchar(50),
	"status_ortu" varchar(50),
	"status_aj" varchar(50),
	"nik" varchar(50),
	"no_rekening" varchar(50),
	"id_wilayah_pembinaan" bigint,
	"nama_wilayah" varchar(100),
	"kantor_id" varchar(10),
	"nama_kantor" varchar(100),
	"id_sdm" bigint,
	"nama_mentor" varchar(100),
	"status_mentor" boolean DEFAULT false NOT NULL,
	"program_donasi" varchar(50),
	"id_program" bigint,
	"program_sebelumnya" varchar(40),
	"harga_program" numeric(20, 2),
	"harga_penyaluran" numeric(20, 2),
	"status_pasangan" boolean DEFAULT false NOT NULL,
	"keterangan_pemberhentian" text,
	"saldo_awal" numeric(20, 2),
	"status_saldo" boolean DEFAULT false NOT NULL,
	"saldo_akhir" numeric(20, 2),
	"status_saldo_akhir" varchar(10),
	"updated_saldo" timestamp with time zone,
	"cek" varchar(100),
	"tunda_penyaluran" varchar(50),
	"id_naik_jenjang" varchar(100),
	"via_input" varchar(50),
	"history" varchar(1),
	"user_stop" varchar(50),
	"via_stop" varchar(50),
	"alasan_aktif" varchar(50),
	"pinjam" text,
	"user_insert" varchar(30),
	"date_insert" timestamp with time zone,
	"user_update" varchar(30),
	"date_update" timestamp with time zone,
	"external_ids" jsonb,
	CONSTRAINT "ajis_pemasangan_id_pemasangan_baru_unique" UNIQUE("id_pemasangan_baru")
);
--> statement-breakpoint
CREATE TABLE "ajis_pemasangan_log" (
	"id_log" bigserial PRIMARY KEY NOT NULL,
	"id_pemasangan_baru" varchar(100) NOT NULL,
	"tgl_pemasangan" date,
	"tgl_pemberhentian_pemasangan" date,
	"id_donatur" varchar(30),
	"nama_donatur" varchar(150),
	"id_anak" varchar(25),
	"nama_anak" varchar(150),
	"id_wilayah_pembinaan" bigint,
	"nama_wilayah" varchar(100),
	"kantor_id" varchar(10),
	"nama_kantor" varchar(100),
	"program_donasi" varchar(50),
	"id_program" bigint,
	"harga_program" numeric(20, 2),
	"harga_penyaluran" numeric(20, 2),
	"keterangan_pemberhentian" text,
	"status_pasangan" boolean,
	"saldo_awal" numeric(20, 2),
	"status_saldo" boolean,
	"status_mentor" boolean,
	"program_sebelumnya" varchar(40),
	"jns_kel" varchar(1),
	"kelas" varchar(50),
	"jenjang_pendidikan" varchar(10),
	"asnaf" varchar(50),
	"status_ortu" varchar(50),
	"status_aj" varchar(50),
	"id_sdm" bigint,
	"nama_mentor" varchar(100),
	"nik" varchar(50),
	"no_rekening" varchar(50),
	"cek" varchar(100),
	"nia_rfo" varchar(50),
	"nama_rfo" varchar(150),
	"user_insert" varchar(30),
	"date_insert" timestamp with time zone,
	"user_update" varchar(30),
	"date_update" timestamp with time zone,
	"updated" timestamp with time zone,
	"deleted" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "ajis_anak" ADD CONSTRAINT "ajis_anak_id_wilayah_pembinaan_ajis_wilayah_pembinaan_id_wilayah_pembinaan_fk" FOREIGN KEY ("id_wilayah_pembinaan") REFERENCES "public"."ajis_wilayah_pembinaan"("id_wilayah_pembinaan") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ajis_anak" ADD CONSTRAINT "ajis_anak_kantor_id_ajis_kantor_oid_fk" FOREIGN KEY ("kantor_id") REFERENCES "public"."ajis_kantor"("oid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ajis_anak" ADD CONSTRAINT "ajis_anak_id_sdm_sdm_wilayah_id_sdm_fk" FOREIGN KEY ("id_sdm") REFERENCES "public"."sdm_wilayah"("id_sdm") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ajis_data_prestasi" ADD CONSTRAINT "ajis_data_prestasi_id_anak_ajis_anak_id_anak_fk" FOREIGN KEY ("id_anak") REFERENCES "public"."ajis_anak"("id_anak") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ajis_opname" ADD CONSTRAINT "ajis_opname_id_pemasangan_baru_ajis_pemasangan_id_pemasangan_baru_fk" FOREIGN KEY ("id_pemasangan_baru") REFERENCES "public"."ajis_pemasangan"("id_pemasangan_baru") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ajis_pemasangan" ADD CONSTRAINT "ajis_pemasangan_id_anak_ajis_anak_id_anak_fk" FOREIGN KEY ("id_anak") REFERENCES "public"."ajis_anak"("id_anak") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ajis_pemasangan" ADD CONSTRAINT "ajis_pemasangan_id_wilayah_pembinaan_ajis_wilayah_pembinaan_id_wilayah_pembinaan_fk" FOREIGN KEY ("id_wilayah_pembinaan") REFERENCES "public"."ajis_wilayah_pembinaan"("id_wilayah_pembinaan") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ajis_pemasangan" ADD CONSTRAINT "ajis_pemasangan_kantor_id_ajis_kantor_oid_fk" FOREIGN KEY ("kantor_id") REFERENCES "public"."ajis_kantor"("oid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ajis_pemasangan" ADD CONSTRAINT "ajis_pemasangan_id_sdm_sdm_wilayah_id_sdm_fk" FOREIGN KEY ("id_sdm") REFERENCES "public"."sdm_wilayah"("id_sdm") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "ajis_anak_scope_idx" ON "ajis_anak" USING btree ("kantor_id","id_wilayah_pembinaan","status_anak_juara");--> statement-breakpoint
CREATE INDEX "ajis_anak_caj_idx" ON "ajis_anak" USING btree ("kantor_id","id_wilayah_pembinaan") WHERE status_anak_juara = 'caj' AND aktif;--> statement-breakpoint
CREATE INDEX "ajis_anak_nia_rfo_book_idx" ON "ajis_anak" USING btree ("nia_rfo_book");--> statement-breakpoint
CREATE INDEX "ajis_anak_sdm_idx" ON "ajis_anak" USING btree ("id_sdm");--> statement-breakpoint
CREATE INDEX "ajis_anak_nama_trgm_idx" ON "ajis_anak" USING gin ("nama_lengkap" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "ajis_data_prestasi_anak_idx" ON "ajis_data_prestasi" USING btree ("id_anak","tgl" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "ajis_opname_natural_idx" ON "ajis_opname" USING btree ("tahun","id_pemasangan_baru");--> statement-breakpoint
CREATE INDEX "ajis_opname_pemasangan_idx" ON "ajis_opname" USING btree ("id_pemasangan_baru");--> statement-breakpoint
CREATE INDEX "ajis_opname_saldo_habis_idx" ON "ajis_opname" USING btree ("tahun","kantor_id") WHERE saldo_akhir_genap <= 0;--> statement-breakpoint
CREATE INDEX "ajis_pemasangan_tahun_kantor_idx" ON "ajis_pemasangan" USING btree ("tahun","kantor_id","status_pasangan");--> statement-breakpoint
CREATE INDEX "ajis_pemasangan_aktif_idx" ON "ajis_pemasangan" USING btree ("kantor_id","tahun") WHERE status_pasangan;--> statement-breakpoint
CREATE INDEX "ajis_pemasangan_anak_idx" ON "ajis_pemasangan" USING btree ("id_anak","tahun");--> statement-breakpoint
CREATE INDEX "ajis_pemasangan_donatur_idx" ON "ajis_pemasangan" USING btree ("id_donatur","tahun");--> statement-breakpoint
CREATE INDEX "ajis_pemasangan_nia_rfo_idx" ON "ajis_pemasangan" USING btree ("nia_rfo","tahun");--> statement-breakpoint
CREATE INDEX "ajis_pemasangan_keyset_idx" ON "ajis_pemasangan" USING btree ("nama_anak","id");--> statement-breakpoint
CREATE INDEX "ajis_pemasangan_nama_anak_trgm_idx" ON "ajis_pemasangan" USING gin ("nama_anak" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "ajis_pemasangan_nama_donatur_trgm_idx" ON "ajis_pemasangan" USING gin ("nama_donatur" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "ajis_pemasangan_log_pemasangan_idx" ON "ajis_pemasangan_log" USING btree ("id_pemasangan_baru");--> statement-breakpoint
CREATE INDEX "ajis_pemasangan_log_anak_idx" ON "ajis_pemasangan_log" USING btree ("id_anak");