CREATE TABLE "ajis_input_donasi" (
	"id_input_donasi" bigserial PRIMARY KEY NOT NULL,
	"id_pemasangan_baru" varchar(100) NOT NULL,
	"tgl_transaksi" date,
	"id_anak" varchar(25),
	"nama_anak" varchar(150),
	"id_donatur" varchar(30),
	"nama_donatur" varchar(150),
	"program_donasi" varchar(50),
	"id_program" bigint,
	"qty" smallint,
	"pilihan_donasi" numeric(20, 2),
	"nominal_donasi" numeric(20, 2),
	"bulan" smallint,
	"tahun" smallint,
	"periode" varchar(10),
	"transid" varchar(50),
	"detailid" smallint,
	"kantor_id" varchar(10),
	"nama_kantor" varchar(100),
	"id_wilayah_pembinaan" bigint,
	"nama_wilayah" varchar(100),
	"jenis" varchar(5),
	"jenjang_pendidikan" varchar(10),
	"jns_kel" varchar(1),
	"asnaf" varchar(50),
	"nik" varchar(50),
	"via_input" varchar(100),
	"user_insert" varchar(30),
	"date_insert" timestamp with time zone,
	"user_update" varchar(30),
	"date_update" timestamp with time zone,
	"external_ids" jsonb,
	CONSTRAINT "ajis_input_donasi_jenis_check" CHECK (jenis IS NULL OR jenis IN ('trans', 'saldo'))
);
--> statement-breakpoint
CREATE TABLE "ajis_penyaluran" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"id_penyaluran" varchar(50) NOT NULL,
	"id_pemasangan_baru" varchar(100),
	"tgl_penyaluran" date,
	"id_anak" varchar(25),
	"nama_anak" varchar(150),
	"nik" varchar(50),
	"jenjang_pendidikan" varchar(10),
	"kelas" varchar(50),
	"jns_kel" varchar(1),
	"asnaf" varchar(50),
	"id_donatur" varchar(30),
	"nama_donatur" varchar(150),
	"id_sdm" bigint,
	"nama_sdm" varchar(100),
	"id_wilayah_pembinaan" bigint,
	"nama_wilayah" varchar(100),
	"kantor_id" varchar(10),
	"nama_kantor" varchar(100),
	"program_donasi" varchar(50),
	"id_program" bigint,
	"nominal_penyaluran" numeric(20, 2),
	"nominal_hpp" numeric(20, 2),
	"saldo_akhir_ganjil" numeric(20, 2),
	"bulan" smallint,
	"tahun" smallint,
	"periode" varchar(10),
	"transid" varchar(50),
	"detailid" smallint,
	"id_input_donasi" bigint,
	"jenis" varchar(50),
	"status_akhir" boolean DEFAULT false NOT NULL,
	"status_tersalurkan" boolean DEFAULT false NOT NULL,
	"via_input" varchar(10),
	"alamat" text,
	"no_rekening" varchar(50),
	"pemilik_rekening" varchar(50),
	"nama_bank" varchar(50),
	"tempat_lahir" varchar(50),
	"no_kartu_keluarga" varchar(50),
	"desaid" varchar(10),
	"nama_desa" varchar(100),
	"nama_kecamatan" varchar(100),
	"nama_kabupaten" varchar(100),
	"nama_propinsi" varchar(100),
	"user_insert" varchar(30),
	"date_insert" timestamp with time zone,
	"user_update" varchar(30),
	"date_update" timestamp with time zone,
	"external_ids" jsonb,
	CONSTRAINT "ajis_penyaluran_natural_uq" UNIQUE("id_penyaluran","id_pemasangan_baru","bulan","tahun"),
	CONSTRAINT "ajis_penyaluran_via_input_check" CHECK (via_input IS NULL OR via_input IN ('massal', 'single'))
);
--> statement-breakpoint
CREATE TABLE "ajis_view_ajuan" (
	"id_ajuan" bigserial PRIMARY KEY NOT NULL,
	"tgl_ajuan" date,
	"kantor_id" varchar(10),
	"nama_kantor" varchar(100),
	"id_wilayah_pembinaan" bigint,
	"nama_wilayah" varchar(200),
	"id_donatur" varchar(30),
	"nama_donatur" varchar(200),
	"oid_donatur" varchar(10),
	"kantor_donatur" varchar(50),
	"jenis_kelamin_donatur" varchar(1),
	"jenis_donatur" varchar(100),
	"hp" varchar(50),
	"program_donasi" varchar(80),
	"nia_rfo" varchar(30),
	"nama_rfo" varchar(80),
	"id_pemasangan_baru" varchar(100),
	"id_anak" varchar(30),
	"nama_anak_asal" varchar(200),
	"jns_kelamin" varchar(1),
	"alasan_pergantian" varchar(200),
	"id_anak_pengganti" varchar(30),
	"nama_anak_pengganti" varchar(200),
	"keterangan" varchar(200),
	"tipe_ganti" varchar(20),
	"pindah_saldo" numeric(20, 2),
	"approve_funding" varchar(1),
	"tgl_approve_funding" timestamp with time zone,
	"alasan_reject" text,
	"status_eksekusi" boolean,
	"tgl_eksekusi" date,
	CONSTRAINT "ajis_view_ajuan_approve_funding_check" CHECK (approve_funding IS NULL OR approve_funding IN ('t', 'n', 'y'))
);
--> statement-breakpoint
CREATE TABLE "transaksi" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"transid" varchar(50) NOT NULL,
	"detailid" smallint NOT NULL,
	"jenis_transaksi" varchar(10),
	"did" varchar(30),
	"nama_donatur" varchar(150),
	"progid" varchar(6),
	"id_program" bigint,
	"nama_program" varchar(100),
	"perkiraan_rp" numeric(20, 2),
	"harga_program" numeric(20, 2),
	"tgl_donasi" date,
	"tgl_transaksi" date,
	"oid_transaksi" varchar(10),
	"oid_donatur" varchar(10),
	"kantor_transaksi" varchar(100),
	"kantor_donatur" varchar(100),
	"kantor_ijis" varchar(100),
	"kantor_id_ijis" varchar(10),
	"jml_anak_ijis" smallint,
	"vbayarid" varchar(100),
	"mbayarid" varchar(100),
	"nik_rfo" varchar(15),
	"nama_rfo" varchar(50),
	"valid4" varchar(50),
	"nik_claim" varchar(14),
	"jid_claim" varchar(6),
	"nama_claim" varchar(50),
	"approved_claim" boolean DEFAULT false NOT NULL,
	"approved_trans" boolean DEFAULT false NOT NULL,
	"atas_nama" text,
	"date_generate" timestamp with time zone,
	"keterangan" text,
	"jml_mustahik" smallint,
	"bulan_disantuni" varchar(50),
	"status_pasang" boolean DEFAULT false NOT NULL,
	"approve_salur" boolean DEFAULT false NOT NULL,
	"ket_approve_salur" text,
	"user_approve_salur" varchar(50),
	"date_approve_salur" timestamp with time zone,
	"deleted_trans" boolean DEFAULT false NOT NULL,
	"deleted_detail" boolean DEFAULT false NOT NULL,
	"review" boolean DEFAULT false NOT NULL,
	"id_review" varchar(50),
	"cicilan" boolean DEFAULT false NOT NULL,
	"bulan_salur" smallint,
	"tahun_salur" smallint,
	"selisih_donasi" numeric(20, 2),
	"total_input_donasi" numeric(20, 2),
	"user_insert_cf" varchar(50),
	"user_update_cf" varchar(50),
	"user_insert" varchar(50),
	"date_insert" timestamp with time zone,
	"external_ids" jsonb,
	CONSTRAINT "transaksi_natural_uq" UNIQUE("transid","detailid"),
	CONSTRAINT "transaksi_jenis_check" CHECK (jenis_transaksi IS NULL OR jenis_transaksi IN ('cash', 'noncash', 'bank', 'pccash', 'pcnoncash'))
);
--> statement-breakpoint
ALTER TABLE "ajis_input_donasi" ADD CONSTRAINT "ajis_input_donasi_id_pemasangan_baru_ajis_pemasangan_id_pemasangan_baru_fk" FOREIGN KEY ("id_pemasangan_baru") REFERENCES "public"."ajis_pemasangan"("id_pemasangan_baru") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ajis_penyaluran" ADD CONSTRAINT "ajis_penyaluran_id_pemasangan_baru_ajis_pemasangan_id_pemasangan_baru_fk" FOREIGN KEY ("id_pemasangan_baru") REFERENCES "public"."ajis_pemasangan"("id_pemasangan_baru") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "ajis_input_donasi_pemasangan_idx" ON "ajis_input_donasi" USING btree ("id_pemasangan_baru","tahun","bulan");--> statement-breakpoint
CREATE INDEX "ajis_input_donasi_anak_idx" ON "ajis_input_donasi" USING btree ("id_anak","tahun");--> statement-breakpoint
CREATE INDEX "ajis_input_donasi_kantor_idx" ON "ajis_input_donasi" USING btree ("kantor_id","tahun","bulan");--> statement-breakpoint
CREATE INDEX "ajis_input_donasi_transid_idx" ON "ajis_input_donasi" USING btree ("transid","detailid");--> statement-breakpoint
CREATE INDEX "ajis_input_donasi_tgl_brin" ON "ajis_input_donasi" USING brin ("tgl_transaksi");--> statement-breakpoint
CREATE INDEX "ajis_penyaluran_pemasangan_idx" ON "ajis_penyaluran" USING btree ("id_pemasangan_baru","tahun","bulan");--> statement-breakpoint
CREATE INDEX "ajis_penyaluran_kantor_idx" ON "ajis_penyaluran" USING btree ("kantor_id","tgl_penyaluran" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "ajis_penyaluran_pending_idx" ON "ajis_penyaluran" USING btree ("kantor_id","tahun","bulan") WHERE NOT status_tersalurkan;--> statement-breakpoint
CREATE INDEX "ajis_penyaluran_tgl_brin" ON "ajis_penyaluran" USING brin ("tgl_penyaluran");--> statement-breakpoint
CREATE INDEX "ajis_view_ajuan_antrian_idx" ON "ajis_view_ajuan" USING btree ("nia_rfo","tgl_ajuan" DESC NULLS LAST) WHERE approve_funding = 't';--> statement-breakpoint
CREATE INDEX "ajis_view_ajuan_scope_idx" ON "ajis_view_ajuan" USING btree ("kantor_id","tgl_ajuan" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "ajis_view_ajuan_anak_idx" ON "ajis_view_ajuan" USING btree ("id_anak");--> statement-breakpoint
CREATE INDEX "transaksi_did_idx" ON "transaksi" USING btree ("did","tgl_transaksi" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "transaksi_live_idx" ON "transaksi" USING btree ("oid_transaksi","tgl_transaksi" DESC NULLS LAST) WHERE approved_trans AND NOT deleted_trans;--> statement-breakpoint
CREATE INDEX "transaksi_oid_idx" ON "transaksi" USING btree ("oid_transaksi","oid_donatur");--> statement-breakpoint
CREATE INDEX "transaksi_tgl_brin" ON "transaksi" USING brin ("tgl_transaksi");