/**
 * types/survey.ts — TS shapes for the MySQL `ajis_survey` table (transisi
 * track), used by the "Data Survey" feature. Mirrors types/survey-pg.ts field
 * for field, but the MySQL table already exists (not generated by
 * db/schema/*.ts) and its columns are used here directly — no camelCase
 * mapping layer (lib/survey/fields.ts just lists the column names).
 *
 * asnaf_anak, biaya_pendidikan_spp_perbulan and bantuan_rutin_dari_lembaga_lain
 * are NOT NULL in the real MySQL table (no default) — the create route fills a
 * sensible default when the form leaves them blank.
 */

/** Full `ajis_survey` row, as returned by GET /api/anakjuara/survey/[id]. */
export interface AjisSurvey {
  id_survey: number;
  tgl_survey: string | null;
  petugas_survey: string | null;
  id_anak: string;

  // denormalized from ajis_anak at create time
  nama_lengkap: string | null;
  nama_lengkap_ayah: string | null;
  nama_lengkap_ibu: string | null;
  nama_lengkap_wali: string | null;
  nama_kantor: string | null;
  kantor_id: string | null;
  nama_wilayah: string | null;
  id_wilayah_pembinaan: string | null;
  asnaf: string | null;
  alamat: string | null;
  jns_kel: string | null;
  jenjang_pendidikan: string | null;
  tgl_pengajuan: string | null;
  status_anak: string | null;

  // filled in on the survey form itself — ajis_anak has no equivalent columns
  nama_propinsi: string;
  nama_kabupaten: string;
  nama_kecamatan: string;
  nama_desa: string;

  hasil_kesimpulan_survey: string | null;

  // household assets & conditions
  kepemilikan_tanah: string | null;
  kepemilikan_rumah: string | null;
  kondisi_dinding_rumah: string | null;
  kondisi_lantai_rumah: string | null;
  kepemilikan_kendaraan: string | null;
  kepemilikan_barang_elektronik: string | null;
  kepemilikan_tabungan: string | null;
  pekerjaan_kepala_keluarga: string | null;
  rata_rata_penghasilan_perbulan: string | null;
  makan_2x: string | null;
  nama_kepala_keluarga: string | null;
  pendidikan_terakhir_kepala_keluarga: string | null;
  jml_tanggungan_kepala_keluarga: number | null;
  sumber_air_bersih: string | null;
  jamban_dan_saluran_limbah: string | null;
  tempat_pembuangan_sampah: string | null;
  terdapat_perokok: string | null;
  terdapat_konsumen_miras: string | null;
  terdapat_persediaan_obat_p3k: string | null;
  makan_buah_dan_sayur_tiap_hari: string | null;
  shalat_5_waktu: string | null;
  membaca_alquran: string | null;
  majelis_taklim: string | null;
  membaca_koran: string | null;
  aktif_sebagai_pengurus_organisasi: string | null;

  asnaf_anak: 'yatim' | 'piatu' | 'dhuafa';
  biaya_pendidikan_spp_perbulan: number;
  bantuan_rutin_dari_lembaga_lain: 'tidak' | 'ada';
  jml_bantuan_rutin_dari_lembaga_lain: number | null;
  resume_deskriptif: string | null;

  user_insert: string | null;
  date_insert: string | null;
  user_update: string | null;
  date_update: string | null;
}

/** Summary columns for GET /api/anakjuara/survey (list view). */
export interface AjisSurveyListItem {
  id_survey: number;
  tgl_survey: string | null;
  petugas_survey: string | null;
  id_anak: string;
  nama_lengkap: string | null;
  jns_kel: string | null;
  jenjang_pendidikan: string | null;
  kantor_id: string | null;
  nama_kantor: string | null;
  id_wilayah_pembinaan: string | null;
  nama_wilayah: string | null;
  asnaf: string | null;
  hasil_kesimpulan_survey: string | null;
  asnaf_anak: 'yatim' | 'piatu' | 'dhuafa' | null;
  date_insert: string | null;
}

/** Query params accepted by GET /api/anakjuara/survey. */
export interface AjisSurveyListParams {
  q?: string;
  hasil_kesimpulan_survey?: string;
  id_wilayah_pembinaan?: string;
  page?: string | number;
  limit?: string | number;
}

/**
 * Body accepted by POST (create) and PUT (update). `id_anak` is required on
 * create (used to look up + denormalize the child) and immutable afterward.
 */
export type AjisSurveyInput = Partial<Omit<AjisSurvey, 'id_survey' | 'user_insert' | 'date_insert' | 'user_update' | 'date_update'>> & {
  id_anak?: string;
};

export interface AjisSurveyListResponse {
  data: AjisSurveyListItem[];
  total: number;
  page: number;
  limit: number;
}

export interface AnakLookupItem {
  id_anak: string;
  nama_lengkap: string;
}
